# Generated by Django 5.2.12 on 2026-03-05 03:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("deviceid", models.AutoField(primary_key=True, serialize=False)),
                ("user_created", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "device_class",
                    models.CharField(blank=True, db_column="class", max_length=50),
                ),
                ("NFP", models.IntegerField(blank=True, null=True)),
                ("stell_sym", models.BooleanField(blank=True, null=True)),
                ("date_created", models.DateField(blank=True, null=True)),
                ("date_updated", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "devices",
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "publicationid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "correspauthor_firstname",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "correspauthor_lastname",
                    models.CharField(blank=True, max_length=100),
                ),
                ("citation", models.TextField(blank=True)),
                ("DOI", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "publications",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Admin must approve this account before the user can upload or query data.",
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("configid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("user_created", models.CharField(blank=True, max_length=100)),
                ("NFP", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("provenance", models.CharField(blank=True, max_length=200)),
                ("m", models.TextField(blank=True)),
                ("n", models.TextField(blank=True)),
                ("stell_sym", models.BooleanField(blank=True, null=True)),
                ("toroidal_flux", models.FloatField(blank=True, null=True)),
                ("aspect_ratio", models.FloatField(blank=True, null=True)),
                ("major_radius", models.FloatField(blank=True, null=True)),
                ("minor_radius", models.FloatField(blank=True, null=True)),
                ("volume", models.FloatField(blank=True, null=True)),
                ("volume_averaged_beta", models.FloatField(blank=True, null=True)),
                ("volume_averaged_B", models.FloatField(blank=True, null=True)),
                ("total_toroidal_current", models.FloatField(blank=True, null=True)),
                ("RBC", models.TextField(blank=True)),
                ("ZBS", models.TextField(blank=True)),
                ("RBS", models.TextField(blank=True)),
                ("ZBC", models.TextField(blank=True)),
                ("current_specification", models.CharField(blank=True, max_length=100)),
                ("pressure_profile_type", models.CharField(blank=True, max_length=100)),
                ("pressure_profile_data1", models.TextField(blank=True)),
                ("pressure_profile_data2", models.TextField(blank=True)),
                ("current_profile_type", models.CharField(blank=True, max_length=100)),
                ("current_profile_data1", models.TextField(blank=True)),
                ("current_profile_data2", models.TextField(blank=True)),
                ("iota_profile_type", models.CharField(blank=True, max_length=100)),
                ("iota_profile_data1", models.TextField(blank=True)),
                ("iota_profile_data2", models.TextField(blank=True)),
                ("average_elongation", models.FloatField(blank=True, null=True)),
                ("Z_excursion", models.FloatField(blank=True, null=True)),
                ("R_excursion", models.FloatField(blank=True, null=True)),
                (
                    "config_class",
                    models.CharField(blank=True, db_column="class", max_length=50),
                ),
                ("date_created", models.DateField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        db_column="deviceid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.device",
                    ),
                ),
            ],
            options={
                "db_table": "configurations",
            },
        ),
        migrations.CreateModel(
            name="DescRun",
            fields=[
                ("descrunid", models.AutoField(primary_key=True, serialize=False)),
                ("user_created", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("provenance", models.CharField(blank=True, max_length=200)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("initialization_method", models.CharField(blank=True, max_length=200)),
                ("l_rad", models.IntegerField(blank=True, null=True)),
                ("m_pol", models.IntegerField(blank=True, null=True)),
                ("n_tor", models.IntegerField(blank=True, null=True)),
                ("l_grid", models.IntegerField(blank=True, null=True)),
                ("m_grid", models.IntegerField(blank=True, null=True)),
                ("n_grid", models.IntegerField(blank=True, null=True)),
                ("inputfilename", models.CharField(blank=True, max_length=200)),
                ("outputfile", models.CharField(blank=True, max_length=200)),
                ("profile_rho", models.TextField(blank=True)),
                ("current_specification", models.CharField(blank=True, max_length=100)),
                ("iota_profile", models.TextField(blank=True)),
                ("iota_max", models.FloatField(blank=True, null=True)),
                ("iota_min", models.FloatField(blank=True, null=True)),
                ("current_profile", models.TextField(blank=True)),
                ("pressure_profile", models.TextField(blank=True)),
                ("pressure_max", models.FloatField(blank=True, null=True)),
                ("pressure_min", models.FloatField(blank=True, null=True)),
                ("D_Mercier", models.TextField(blank=True)),
                ("D_Mercier_min", models.FloatField(blank=True, null=True)),
                ("D_Mercier_max", models.FloatField(blank=True, null=True)),
                ("date_created", models.DateField(blank=True, null=True)),
                ("vacuum", models.BooleanField(blank=True, null=True)),
                ("spectral_indexing", models.CharField(blank=True, max_length=50)),
                ("sym", models.BooleanField(blank=True, null=True)),
                ("surface_plot", models.CharField(blank=True, max_length=200)),
                ("boozer_plot", models.CharField(blank=True, max_length=200)),
                ("plot3d", models.CharField(blank=True, max_length=200)),
                (
                    "config_name",
                    models.ForeignKey(
                        blank=True,
                        db_column="config_name",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.configuration",
                        to_field="name",
                    ),
                ),
                (
                    "publicationid",
                    models.ForeignKey(
                        blank=True,
                        db_column="publicationid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "db_table": "desc_runs",
            },
        ),
        migrations.CreateModel(
            name="VmecRun",
            fields=[
                ("vmecrunid", models.AutoField(primary_key=True, serialize=False)),
                ("user_created", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("provenance", models.CharField(blank=True, max_length=200)),
                ("vmec_version", models.CharField(blank=True, max_length=50)),
                ("mpol", models.IntegerField(blank=True, null=True)),
                ("mtor", models.IntegerField(blank=True, null=True)),
                ("ns_array", models.TextField(blank=True)),
                ("niter_array", models.TextField(blank=True)),
                ("ftol_array", models.TextField(blank=True)),
                ("iotaf", models.TextField(blank=True)),
                ("inputfile", models.CharField(blank=True, max_length=200)),
                ("outputfile", models.CharField(blank=True, max_length=200)),
                ("date_created", models.DateField(blank=True, null=True)),
                (
                    "config_name",
                    models.ForeignKey(
                        blank=True,
                        db_column="config_name",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.configuration",
                        to_field="name",
                    ),
                ),
                (
                    "publicationid",
                    models.ForeignKey(
                        blank=True,
                        db_column="publicationid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.publication",
                    ),
                ),
            ],
            options={
                "db_table": "vmec_runs",
            },
        ),
    ]
